### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by ircer** [jjyg/rbircd#2]
```
root@li140-48:~/rbircd# ruby -r ircd.rb -e 'Ircd.run("ircd.conf", "irc_log.txt")'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- ircd.rb (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
```

**Comment by ircer** [comment]
@jjyg any idea?

**Comment by ircer** [comment]
@jjyg ?

**Comment by jjyg** [comment]
try with the option ruby -r ./ircd.rb

**Comment by jjyg** [comment]
Also, you may want to run that as a non-root user.
